
# https://www.dropbox.com/s/e25p5zi1twsdvse/Copia%20de%20input029.txt?dl=0
INPUT = "dcbbbccdbdbddcddadadaacaaabbdbabbabdbdbcacdcbbdddbbccdacdbcadcacdcaadbcdcaaabbcdbbcdcddbabdccdddaddbdabbdbbdddddaabacbbdbdaddccabbacacacdbacddacacbadcbddbacaddaabbbaaadccbadabbdbdcabacdbcacbaadccbbabcdbbabbddadcaaacacdccdbbbddaadcdddcaacbcbbccdbcdaabaabbddbccacddaccbbbccbddbcddddddaddbbbdbbcaabbdadcdadcdcdbaabbbadcadaabbcccadcddacbbbaaaccddbdaccacbbadbdbdaadaccadcbcbdbbbbcccbcadcdabbbddaaadaacadcbcbaddbddcadaddbcaabbbdaacbcacacbbcadcbaabdacadccdbbcbdddacaccbcbcdcaaabcbcdabadcabcadbababacaaacadcadacadaadccbaddabdcaaacbabdcddaadcbababcccbadadbadcbcbcdcbbbaccaaaccbbbdbdababdacdcbdabcdadcdbbbaddacaaabbbdacacdddbcddbcacbcbddcbabaccabbaddaadbabaadcbdccacdcacbbdcadbcaacdbdbbbcdccbcacdbaaaaccdaacdccabadaaccbbbccadaaadbccabadcaabccbcbdcdbbdaabdcdccabbbcbccdacbcdbbbadccdbcabcdbabcadaccbbbbcbbdacabbdaddcbcdaccadbcdcccdcdaabacdbcbcdacbacccadcbdacacabccbbbbbbcbdaacddcabbbccadabbabbbadcabadcdcccdbdcaaaaccdcdbcbcababbbdcdabbbdcddcaccbbdaccaddabcaccbdddbabbacddccdcbcbbccaacbbbaacbbacbaccbacaadbccdccdbadcacbaddacddbdbcaaaabbdaabcccdbbadddbcbddccdbdccdaddbcbcaccdbbddbdcddbdabcadaadbccbbdcdadcbbcbababbbaaacbabcbdcbbabababcdbbdbbaaccdbddcccabacaaaddccbaddabcadbbaddbadbaadddbcdababcddadcacbabccddbcadddacacbcdccbccdbddacabbccabbadaddbdacccdaaabcadbccaabbbdbccadbdaacaaabcadadadcbbcbdaccddacabbaacdbcdacccaadbcadabdaaddcaabbaacaddcabbcbdadaccdabdcbabcaaccddcabddddcccdbdbcaadbddbdbccaaabbcdbcdbddbcdddcacccbdabaddaacaabcbdcdabbdddcabdbbbdabadcddbbcddbcdacadbbbdbaadcbcadacaadcbbcddbaccbcaddacbaadccddddcbadacdcbbcdbaadbbdbabdbbcaaddacdacddadaaabbabbaddaccbdabccbababcbbadcccdcdabbaccabccabcbbabcdacacaabdacccddcaabaadcdabcbccddddcdcacabddcccaabbdcaacbbbabbbccdbcddcddbadbbbbcacbacdaaadbaabddccdadaadcdcbacbaaaadacaabdbbcacaccdaacccababaccdbdcbbababcbcdbddbbaccdbdcbdbdbbdbdccccddcbdadbadbbbdacbaadcdddcbbcacbdbdacdcdbcacbcdbacccddadcdbabdaabdbccbbcabadadcbdacabbdcbcbcdbaccdabdbbcaddbacacdabcdbdcdccaddacddddddabdabdcacddccdadabdbaabbcbbadcccbccdabcbdadcaaaabdabcadacacbdacdbcacbadbaaaacdabbadcccdadcdadbbbcabbbcdddcccccadaccdaabbbcbcabbbcbdadbdccdbdcddaacaaadbbacbdadcdadaaccacdcdbbdddaabbaadddbcccacdabbcabaccbcccbcdaabdbdabcccdbdabbbcaacabaaaaacbddbbddcbbaaaddcdacbcbbdbbbabcadabbaabaccbabdaaadcbdbbcabdcadbcdaacddccbaadbcacddddbcbcbdabbadaadcccddddcdaddcbbaddaaabdadabaadabbcbdbdcadccdddcdbbabdadccdbabdbddbdbbbddaaddaacbcadbaacccaacadbdcccbcdcbbdbccbbcbdcaabdbdcacccdcccbccaaaccaaaccbbdacdadbcdbbbccaacdbcabccaacaaadbaaddcdbbabdbcdbacadcaaabaacdaaadabacaadcaadbadbaacbcddcbdcbcbbadaddbadcddacbadadaaacdadcdbccbbcbddaabddadbdadbadcddcacadcdddddacababccdadbabcacdcbddbbaaadacddbbdcaabbbbdcbcaabadbacdddbaabddacdcbdaadbdddaacbaabcbbbcccdcbccbaaadadadbabdcbcaabaacbaabaaaddaaaccddbcdbbcabcaaacdacdacbbddcdabaadccaabadcbdbdbabdbbddddcdabadddaddcaaddcdcdccdbdbaddacdbdaddcbbbdcbabbacbcadaccaaabcabccbdcbbbdcdcbdabcdddccdaadbdcdbbadcaadacabcaabccbcdabccdbbcbbcdadbcccbbadbcadacabcdacadcadbcdbdbccdcbacccdcbdadbdbaccaabdcbacadcbacccadddbabcdacbbccdabdaabacdbaccbbaddacdacdaaabddaadcbccacddcdcdbaacaccccdaabbbbcbacbddabcccacdadddbccccccccbaddbbabbcdcaaabdbbbcacaccdbaacccabcdcdadccddddcbdcbabcababbdbbadacaccbdcbcbddcddcbaddadadcbbddbabbbcdbbccdbcacdbbdacbcbdacddbadcbcbbcbdabcbdcccbbdddbabbdacddacbdcbbaccbacddbbcadadacddcccbbabbbdacdaadabaacadadcccaadbcaddcdccbdaccaabbbadbacbbcbcadcdacacbacbddaacdbcabcabbdabbdbabcaaddbaabcddabacdbcbbdccdcadddbbdabcadbcabdbcaccacbddbbadcdaabdbadcbbabcaadbcbbddcdbccddddaccbaaadbaddacdccdbcabdaaddcadcdcbcaddbabaabadcabcadacdbadcbabcdbddadcdbaadbacbbacbbaaadabcbbbcdbabaaadcdcccbbaabbdacbbacddcbcbaabbccdcaaccbbcbdacbbdacdddccaaabcaabadabbacabadbacdbcccdadbcdbbcadbdcabaddccccdbdcddbbdbaadacdabaddcacbbabcabbddacdbadabccacdbdbcbcbcdcdacbaacdcbcbcaaacaddbaacadabdbcabbcccdcaabcdbacbcaccadabcacbbacaacabbccbdadabddddaababcbabcdacddcdadddccbaabcdbdbbabccdcbdcdbbcddacabdbaccdbdbcbbcadcddacdcbbbaacdccddbcadddcaddbcadcbababcddadaacababcacbbbdabccabbacaabbadccbbbcddcdcabbcbdddadcbddadaccadacaabcbabcdbdbcdbddcccbbbcdcdcaaabdbabcddcddabaaadadbcdddccdcbcdccdaabbbdccbbdadbadaadcbad"

LETRA_A = []
LETRA_B = []
LETRA_C = []
LETRA_D = []

def init():
    for letra in INPUT:
        
        if letra.lower() == 'a':
            LETRA_A.append(letra)
        elif letra.lower() == 'b':
            LETRA_B.append(letra)
        elif letra.lower() == 'c':
            LETRA_C.append(letra)
        elif letra.lower() == 'd':
            LETRA_D.append(letra)
        
    
    soma_A_C = len(LETRA_A) + len(LETRA_C)
    soma_B_D = len(LETRA_B) + len(LETRA_D)
    
    if (soma_A_C % 2 == 0) and (soma_B_D % 2 == 0):
        return True
    else:
        return False
    
    
print(init())